theme: jekyll-theme-minimal
title: Yihan Zhang 
description: A full-stack IC (integrated circuit) engineer working on multi-disciplinery projects
author_photo: assets/author_photo.png
carousels:
	- images:
		- image: assets/A.jpg
		- image: assets/B.jpg
		- image: assets/C.jpg